services:
  mysql:
    image: mysql:8.0
    container_name: mysql_projeqtor
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: projeqtor 
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin 

  projeqtor:
    build: ./projeqtor
    container_name: projeqtor
    ports:
      - 8888:80
    volumes:
      - /var/www/html
    links:
      - mysql_projeqtor

networks:
  pnet: {}
